#!/bin/bash

# get the nginx tarball, untar it
curl -LO http://nginx.org/download/nginx-1.3.4.tar.gz
tar xf nginx-1.3.4.tar.gz

# move nginx to src
mv nginx-1.3.4 src

# move to source
cd src/

# define directory for config file
DIR=$(pwd) # current directory
PREFIX=$(dirname $DIR) # one up from current directory

# compile nginx
./configure --prefix=$PREFIX \
--add-module=../nginx-upload-module \
--add-module=../echo-nginx-module \
--with-debug \
--with-http_stub_status_module \
--with-http_flv_module \
--with-http_ssl_module \
--with-http_dav_module \
--with-http_gzip_static_module \
--with-http_realip_module \
--with-mail \
--with-mail_ssl_module \
--with-ipv6 \
--with-pcre 

# run makefile
sudo make
sudo make install
